name: Newman + Deploy Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  run-newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install newman + reporter
        run: npm i -g newman newman-reporter-htmlextra

      - name: Run newman and produce HTML
        run: |
          mkdir -p docs
          newman run Petstore_Collection.json \
            -e Petstore-Demo.postman_environment.json \
            --reporters "cli,htmlextra" \
            --reporter-htmlextra-export docs/index.html

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: run-newman
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
